{{- if .Values.vault.filePersistence.create -}}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "vault.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.vault.dev }}
        command: ["vault", "server", "-dev", "-dev-listen-address", "[::]:8200"]
        {{- else }}
        command: ["vault", "server", "-config", "/vault/config/config.json"]
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config/
        - name: vault-root
          mountPath: /root/
        {{- range .Values.vault.customSecrets }}
        - name: {{ .secretName }}
          mountPath: {{ .mountPath }}
        {{- end }}
        - name: file-backend
          mountPath: "{{ .Values.vault.config.storage.file.path }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "vault.fullname" . }}
                  release: {{ .Release.Name | quote }}
      volumes:
        - name: vault-config
          configMap:
            name: "{{ template "vault.fullname" . }}-config-{{ .Release.Revision }}"
        - name: vault-root
          emptyDir: {}
        {{- range .Values.vault.customSecrets }}
        - name: {{ .secretName }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: file-backend
      spec:
        accessModes:
{{ toYaml .Values.vault.filePersistence.accessModes | indent 10 }}
        {{- if .Values.vault.filePersistence.storageClass }}
        storageClassName: "{{ .Values.vault.filePersistence.storageClass }}"
        {{- else }}
        storageClassName: ""
        {{- end }}
        resources:
          requests:
            storage: "{{ .Values.vault.filePersistence.size }}"
{{- end -}}